smtp:
  server:
    addr: ":21025"
    domain: "shieldemail.ddns.net"
    read_timeout_seconds: 10
    write_timeout_seconds: 10
    max_message_bytes: 1024
    max_recipients: 50
    allow_insecure_auth: true

  client: {}

telegram:
  token: ""

kafka: {}