smtp:
  server:
    addr: ":21025"
    domain: "shieldemail.ddns.net"
    read_timeout_seconds: 10
    write_timeout_seconds: 10
    max_message_bytes: 1024
    max_recipients: 50
    allow_insecure_auth: true

  client: {}

telegram:
  token: "your_Bot_token"
  debug: true
  webhook_mode:
    enabled: false
    port: 8443
    cert: ".deploy/cert.pem"
    key: ".deploy/cert.key"

rabbitmq:
  dsn: "amqp://guest:guest@rabbitmq:5672/"

database:
  hostname: "mongo"
  port: 27017
  username: "root"
  password: "example"