version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq/mnesia'
    networks:
      - app-tier

  mongo:
    image: mongo:5.0.5-focal
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-tier

  tg_bot:
    build:
      dockerfile: build/package/Dockerfile
      context: ../.
    volumes:
      - './config.docker.yaml:/config.yaml'
    command:
      - tg_bot
      - -c
      - config.yaml
    networks:
      - app-tier

  receiver:
    build:
      dockerfile: build/package/Dockerfile
      context: ../.
    volumes:
      - './config.docker.yaml:/config.yaml'
    ports:
      - '21025:21025'
    command:
      - receiver
      - -c
      - config.yaml
    networks:
      - app-tier
    restart: "no"

volumes:
  rabbitmq_data:
    driver: local
  mongo_data:
    driver: local


networks:
  app-tier:
    driver: bridge