# run local with build by override original config
# docker-compose -f .deploy/docker-compose.yml -f .deploy/docker-compose.dev.yml
version: "3"

services:
  tg_bot:
    build:
      dockerfile: build/package/Dockerfile
      context: ../.

  receiver:
    build:
      dockerfile: build/package/Dockerfile
      context: ../.
