# run production by override original config
# docker-compose -f .deploy/docker-compose.yml -f .deploy/docker-compose.prod.yml up
version: "3"

services:
  tg_bot:
    image: "ghcr.io/requiemofthesouls/pigeomail:${PIGEOMAIL_VERSION}"
    build:
      dockerfile: build/package/Dockerfile
      context: ../.
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    ports:
      - '8433:8433'
    restart: always
    volumes:
      - './config.docker.yaml:/config.yaml'
      - './cert.pem:/cert.pem'
      - './cert.key:/cert.key'
    command:
      - tg_bot
      - -c
      - config.yaml
    networks:
      - pigeomail_backend

  receiver:
    image: "ghcr.io/requiemofthesouls/pigeomail:${PIGEOMAIL_VERSION}"
    build:
      dockerfile: build/package/Dockerfile
      context: ../.
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    volumes:
      - './config.docker.yaml:/config.yaml'
    ports:
      - '25:21025'
    command:
      - receiver
      - -c
      - config.yaml
    networks:
      - pigeomail_backend
    restart: always
