# run production by override original config
# docker-compose -f .deploy/docker-compose.yml -f .deploy/docker-compose.prod.yml up
version: "3"

services:
  tg_bot:
    image: "ghcr.io/requiemofthesouls/pigeomail:${PIGEOMAIL_VERSION}"

  receiver:
    image: "ghcr.io/requiemofthesouls/pigeomail:${PIGEOMAIL_VERSION}"
