name: Deploy release
on:
  push:
    branches:
      - nonexistingbranch
  workflow_dispatch:
    inputs:
      release:
        description: "Choose tag for deploy"
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_DIR }}
            git pull
            bash .deploy/deploy.sh "${{ github.ref_name }}"